<Project Sdk="Microsoft.NET.Sdk.Web">

  <ItemGroup>
    <ProjectReference Include="..\LocalEnterprise.Application\LocalEnterprise.Application.csproj" />
    <ProjectReference Include="..\LocalEnterprise.Infrastructure\LocalEnterprise.Infrastructure.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>8b8652bd-fce2-4c68-b6e7-1b7bcc627db9</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="OpenIddict.AspNetCore" Version="7.6.0" />
    <PackageReference Include="OpenIddict.Server.AspNetCore" Version="7.6.0" />
    <PackageReference Include="OpenIddict.Validation.AspNetCore" Version="7.6.0" />
  </ItemGroup>

</Project>
